global:
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  appEnv: production

enabled: true
componentName: service
envPrefix: OTUS_SERVICE
replicaCount: 1

image:
  repository: example/service
  tag: latest

service:
  port: 8000

database:
  image:
    repository: postgres
    tag: "16"
  username: service
  password: service
  database: service
  persistence:
    enabled: true
    size: 500Mi
    storageClass: ""
  resources: {}

migration:
  enabled: true
  backoffLimit: 6

extraEnv: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
