apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.names.secret }}
  labels:
    {{- include "users-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DB_DBNAME: {{ .Values.db.name | quote }}
