apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.secretName" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.database.password | quote }}
