apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config-map
data:
  APP_ENV: "production"
  APP_NAME: "users-service"

  HTTP_ADDR: ":8000"
  HTTP_SHUTDOWN_TIMEOUT: "5s"

  DB_HOST: "users-db-service"
  DB_PORT: "5432"
  DB_TIMEZONE: "UTC"
