apiVersion: batch/v1
kind: Job
metadata:
  name: users-db-migration-job
spec:
  template:
    spec:
      containers:
        - name: users-db-migration-job
          image: paulrozhkin/otus-microservices-homework-04:latest
          args: [ "migrate" ]
          envFrom:
            - secretRef:
                name: users-secret
              prefix: OTUS_USER_SERVICE_
            - configMapRef:
                name: users-config-map
              prefix: OTUS_USER_SERVICE_
      restartPolicy: Never
  backoffLimit: 4
  