apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
stringData:
  POSTGRES_DB: "user_service"
  POSTGRES_USER: "user_service"
  POSTGRES_PASSWORD: "user_service"

  OTUS_USER_SERVICE_DB_USER: "user_service"
  OTUS_USER_SERVICE_DB_PASSWORD: "user_service"
  OTUS_USER_SERVICE_DB_DBNAME: "user_service"